#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gflags
Version  : 2.2.2
Release  : 29
URL      : https://github.com/gflags/gflags/archive/v2.2.2.tar.gz
Source0  : https://github.com/gflags/gflags/archive/v2.2.2.tar.gz
Summary  : @PACKAGE_DESCRIPTION@
Group    : Development/Tools
License  : BSD-3-Clause
Requires: gflags-bin = %{version}-%{release}
Requires: gflags-lib = %{version}-%{release}
Requires: gflags-license = %{version}-%{release}
BuildRequires : buildreq-cmake

%description
The gflags package contains a C++ library that implements commandline flags processing.
It includes built-in support for standard types such as string and the ability to define
flags in the source file in which they are used.

%package bin
Summary: bin components for the gflags package.
Group: Binaries
Requires: gflags-license = %{version}-%{release}

%description bin
bin components for the gflags package.


%package dev
Summary: dev components for the gflags package.
Group: Development
Requires: gflags-lib = %{version}-%{release}
Requires: gflags-bin = %{version}-%{release}
Provides: gflags-devel = %{version}-%{release}
Requires: gflags = %{version}-%{release}

%description dev
dev components for the gflags package.


%package lib
Summary: lib components for the gflags package.
Group: Libraries
Requires: gflags-license = %{version}-%{release}

%description lib
lib components for the gflags package.


%package license
Summary: license components for the gflags package.
Group: Default

%description license
license components for the gflags package.


%prep
%setup -q -n gflags-2.2.2
cd %{_builddir}/gflags-2.2.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1576081279
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake .. -DBUILD_SHARED_LIBS:BOOL=ON \
-DBUILD_TESTING:BOOL=ON \
-DLIBRARY_INSTALL_DIR:PATH=lib64
make  %{?_smp_mflags}  VERBOSE=1
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
pushd  clr-build

ctest

popd

%install
export SOURCE_DATE_EPOCH=1576081279
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/gflags
cp %{_builddir}/gflags-2.2.2/COPYING.txt %{buildroot}/usr/share/package-licenses/gflags/b2d4ab17f1b8ef9e0646ba932dce81efe3b852ab
pushd clr-build
%make_install
popd
## install_append content
rm -rf %{buildroot}/builddir
chmod a+x %{buildroot}/usr/bin/*
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gflags_completions.sh

%files dev
%defattr(-,root,root,-)
/usr/include/gflags/gflags.h
/usr/include/gflags/gflags_completions.h
/usr/include/gflags/gflags_declare.h
/usr/include/gflags/gflags_gflags.h
/usr/lib64/cmake/gflags/gflags-config-version.cmake
/usr/lib64/cmake/gflags/gflags-config.cmake
/usr/lib64/cmake/gflags/gflags-nonamespace-targets-relwithdebinfo.cmake
/usr/lib64/cmake/gflags/gflags-nonamespace-targets.cmake
/usr/lib64/cmake/gflags/gflags-targets-relwithdebinfo.cmake
/usr/lib64/cmake/gflags/gflags-targets.cmake
/usr/lib64/libgflags.so
/usr/lib64/libgflags_nothreads.so
/usr/lib64/pkgconfig/gflags.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgflags.so.2.2
/usr/lib64/libgflags.so.2.2.2
/usr/lib64/libgflags_nothreads.so.2.2
/usr/lib64/libgflags_nothreads.so.2.2.2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gflags/b2d4ab17f1b8ef9e0646ba932dce81efe3b852ab
