#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gflags
Version  : 2.2.0
Release  : 12
URL      : https://github.com/gflags/gflags/archive/v2.2.0.tar.gz
Source0  : https://github.com/gflags/gflags/archive/v2.2.0.tar.gz
Summary  : @PACKAGE_DESCRIPTION@
Group    : Development/Tools
License  : BSD-3-Clause
Requires: gflags-bin
Requires: gflags-lib
BuildRequires : cmake
BuildRequires : cmake-dev

%description
[![Build Status](https://travis-ci.org/gflags/gflags.svg?branch=master)](https://travis-ci.org/gflags/gflags)
[![Build status](https://ci.appveyor.com/api/projects/status/4ctod566ysraus74/branch/master?svg=true)](https://ci.appveyor.com/project/schuhschuh/gflags/branch/master)

%package bin
Summary: bin components for the gflags package.
Group: Binaries

%description bin
bin components for the gflags package.


%package dev
Summary: dev components for the gflags package.
Group: Development
Requires: gflags-lib
Requires: gflags-bin
Provides: gflags-devel

%description dev
dev components for the gflags package.


%package lib
Summary: lib components for the gflags package.
Group: Libraries

%description lib
lib components for the gflags package.


%prep
%setup -q -n gflags-2.2.0

%build
export LANG=C
mkdir clr-build
pushd clr-build
cmake .. -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS:BOOL=ON -DLIB_INSTALL_DIR:PATH=%{_libdir} -DCMAKE_AR=/usr/bin/gcc-ar -DCMAKE_RANLIB=/usr/bin/gcc-ranlib -DBUILD_SHARED_LIBS:BOOL=ON
make VERBOSE=1  %{?_smp_mflags}
popd

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
ctest

%install
rm -rf %{buildroot}
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
/builddir/.cmake/packages/gflags/1517893d82dfcf97475a559a3d57ec1c
/usr/lib64/cmake/gflags/gflags-config-version.cmake
/usr/lib64/cmake/gflags/gflags-config.cmake
/usr/lib64/cmake/gflags/gflags-targets-noconfig.cmake
/usr/lib64/cmake/gflags/gflags-targets.cmake

%files bin
%defattr(-,root,root,-)
/usr/bin/gflags_completions.sh

%files dev
%defattr(-,root,root,-)
/usr/include/gflags/gflags.h
/usr/include/gflags/gflags_completions.h
/usr/include/gflags/gflags_declare.h
/usr/include/gflags/gflags_gflags.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
